# Generated by Django 4.1.4 on 2023-01-26 22:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField()),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_e164', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=128)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
