# Generated by Django 4.1.4 on 2023-01-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth0_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
