# Generated by Django 4.1.4 on 2023-01-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_auth0_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
