# Generated by Django 4.1.4 on 2023-01-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organization_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
