# Generated by Django 4.1.4 on 2023-01-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_root',
            field=models.BooleanField(default=True),
        ),
    ]
