### Pushes to ECR Repository
name: Build and push

#on: workflow_dispatch
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python manage.py test

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.GH_ACTION_ROLE_ARN }}
          aws-region: us-east-2

      - name: Get ECR Registry
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ steps.ecr-login.outputs.registry }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata for Docker image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ steps.ecr-login.outputs.registry }}/django-starter-v1
          tags: |
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: true